/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminRolesIndexRouteImport } from './routes/_admin/roles/index'
import { Route as AdminPermissionsIndexRouteImport } from './routes/_admin/permissions/index'
import { Route as AdminRolesRoleIdPermissionsRouteImport } from './routes/_admin/roles/$roleId/permissions'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsIndexRoute = AdminPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoleIdPermissionsRoute =
  AdminRolesRoleIdPermissionsRouteImport.update({
    id: '/roles/$roleId/permissions',
    path: '/roles/$roleId/permissions',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/permissions/': typeof AdminPermissionsIndexRoute
  '/roles/': typeof AdminRolesIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof AdminIndexRoute
  '/permissions': typeof AdminPermissionsIndexRoute
  '/roles': typeof AdminRolesIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/permissions/': typeof AdminPermissionsIndexRoute
  '/_admin/roles/': typeof AdminRolesIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_admin/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/unauthorized'
    | '/permissions/'
    | '/roles/'
    | '/users/'
    | '/roles/$roleId/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/not-found'
    | '/signup'
    | '/unauthorized'
    | '/'
    | '/permissions'
    | '/roles'
    | '/users'
    | '/roles/$roleId/permissions'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/unauthorized'
    | '/_admin/'
    | '/_admin/permissions/'
    | '/_admin/roles/'
    | '/_admin/users/'
    | '/_admin/roles/$roleId/permissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/': {
      id: '/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/permissions/': {
      id: '/_admin/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AdminPermissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/$roleId/permissions': {
      id: '/_admin/roles/$roleId/permissions'
      path: '/roles/$roleId/permissions'
      fullPath: '/roles/$roleId/permissions'
      preLoaderRoute: typeof AdminRolesRoleIdPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPermissionsIndexRoute: typeof AdminPermissionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminRolesRoleIdPermissionsRoute: typeof AdminRolesRoleIdPermissionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPermissionsIndexRoute: AdminPermissionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminRolesRoleIdPermissionsRoute: AdminRolesRoleIdPermissionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
